name: Execute Terragrunt
description: ""

inputs:
  working-directory:
    description: The directory to run the command from
    required: true
  command:
    description: The command to run
    required: true
  pr-comment:
    description: Set to true to comment on the PR
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    -
      name: Execute command
      id: terragrunt
      uses: gruntwork-io/terragrunt-action@v3
      with:
        tg_version: ${{ env.TG_INSTALL_TG_VERSION }}
        tf_path: ${{ env.TG_INSTALL_TF_PATH }}
        tg_dir: ${{ inputs.working-directory }}
        tg_command: ${{ inputs.command }}
        tg_comment: 0
        tg_output_capture: 1
    -
      name: Parse result
      id: parse-result
      if: ${{ !cancelled() }}
      uses: actions/github-script@v7
      env:
        TG_DIR: ${{ inputs.working-directory }}
        TG_COMMAND: ${{ inputs.command }}
        TG_ACTION_EXIT_CODE: ${{ steps.terragrunt.outputs.tg_action_exit_code }}
        TG_ACTION_OUTPUT: ${{ steps.terragrunt.outputs.tg_action_output }}
      with:
        script: |
          const succeeded = process.env.TG_ACTION_EXIT_CODE == '0';

          let outcome, outcomeEmoji;
          if (succeeded) {
            outcome = 'succeeded';
            outcomeEmoji = '✅';
          } else {
            outcome = 'failed';
            outcomeEmoji = '❌';
          }

          const actionOutput = process.env.TG_ACTION_OUTPUT.replaceAll('%0A', '\n');

          const commentLines = [
            `### ${outcomeEmoji} terragrunt ${outcome} in \`${process.env.TG_DIR}\``,
            '',
            `Command: \`terragrunt ${process.env.TG_COMMAND}\``,
            '',
          ]

          const planRegex = new RegExp('.*\\[(\.terragrunt-stack\\/)?(?<unit>[^\\]]+)\\] Plan: (?<add>[0-9]+) to add, (?<change>[0-9]+) to change, (?<destroy>[0-9]+) to destroy\..*');

          const summaries = [];
          for (let line of actionOutput.split('\n')) {
            const matches = line.match(planRegex)
            if (matches) {
              summaries.push({
                unit: matches.groups.unit,
                add: matches.groups.add,
                change: matches.groups.change,
                destroy: matches.groups.destroy,
              })
            }
          }

          if (succeeded) {
            let planOverview;
            if (summaries.length == 0) {
              commentLines.push(
                `Overview: No changes`,
                '',
              );
            } else {
              commentLines.push(
                '',
                '| Unit | Add | Change | Destroy |',
                '| ---- | --- | --- | --- |',
              )
              
              for (const summary of summaries) {
                commentLines.push(
                  `| ${summary.unit} | ${summary.add} | ${summary.change} | ${summary.destroy} |`,
                )
              }
            }

            commentLines.push('')
          }

          commentLines.push(
            '<details>',
            '',
            '<summary>Full logs</summary>',
            '',
            '```terraform',
            actionOutput,
            '```',
            '',
            '</details>',
          )

          core.setOutput('comment-body', commentLines.join('\n'));
    -
      name: Comment outcome
      uses: marocchino/sticky-pull-request-comment@v3
      if: |
        !cancelled() &&
        inputs.pr-comment == 'true'
      with:
        recreate: true
        header: tg-command-${{ inputs.working-directory }}
        message: ${{ steps.parse-result.outputs.comment-body }}
