name: Build Terragrunt Matrix
description: Build a matrix of Terragrunt stacks to plan

inputs:
  UNITS_DIR:
    description: Units directory
    required: true
  STACKS_DIR:
    description: Stacks directory
    required: true
  TRIGGER_ALL:
    description: If 'true', skips change detection and marks all stacks as changed
    required: false
    default: 'false'

outputs:
  STACKS:
    description: JSON array of all changed stacks
    value: ${{ steps.final-outputs.outputs.stacks-changed }}

runs:
  using: composite
  steps:
    -
      shell: bash
      id: stack-path-filters
      env:
        STACKS_DIR: ${{ inputs.STACKS_DIR }}
      run: |
        # Build stack path filters

        STACK_PATH_FILTERS=$(${{ github.action_path }}/path-filters.sh)

        echo "::group::Stack path filters"
        echo "$STACK_PATH_FILTERS"
        echo "::endgroup::"

        echo 'filters<<EOF' >> $GITHUB_OUTPUT
        echo "$STACK_PATH_FILTERS" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
    -
      shell: bash
      id: list-all-stacks
      env:
        STACK_PATH_FILTERS: ${{ steps.stack-path-filters.outputs.filters }}
      run: |
        ALL_STACKS=$(echo "$STACK_PATH_FILTERS" | yq -o json -I0 'keys')

        echo "::group::All stacks"
        echo "$ALL_STACKS"
        echo "::endgroup::"

        echo "all-stacks=$ALL_STACKS" >> "$GITHUB_OUTPUT"
    -
      name: Detect unit changes
      uses: dorny/paths-filter@v4
      if: ${{ inputs.TRIGGER_ALL != 'true' }}
      id: unit-changes
      with:
        filters: |
          units:
            - '${{ inputs.UNITS_DIR }}/**'
    -
      name: Detect stack changes
      if: ${{ inputs.TRIGGER_ALL != 'true' }}
      uses: dorny/paths-filter@v4
      id: stack-changes
      with:
        filters: ${{ steps.stack-path-filters.outputs.filters }}
    -
      name: Final outputs
      id: final-outputs
      shell: bash
      env:
        INPUT_ALL: ${{ inputs.TRIGGER_ALL }}
        UNIT_CHANGES: ${{ steps.unit-changes.outputs.changes }}
        STACK_CHANGES: ${{ steps.stack-changes.outputs.changes }}
        ALL_STACKS: ${{ steps.list-all-stacks.outputs.all-stacks }}
      run: |
        echo "::group::Final outputs"

        if [[ "$INPUT_ALL" == "true" ]]; then
          echo "stacks-changed=$ALL_STACKS" | tee -a "$GITHUB_OUTPUT"
          exit 0
        fi

        HAS_UNIT_CHANGES=$(echo "$UNIT_CHANGES" | jq -rc '(. | length) > 0')
        if [[ "$HAS_UNIT_CHANGES" == "true" ]]; then
          echo "stacks-changed=$ALL_STACKS" | tee -a "$GITHUB_OUTPUT"
        else
          echo "stacks-changed=$STACK_CHANGES" | tee -a "$GITHUB_OUTPUT"
        fi

        echo "::endgroup::"
