name: Parse stack info
description: ""

inputs:
  INFO_FILE:
    description: Stack info file to parse
    required: true

outputs:
  aws-account-id:
    description: AWS account ID
    value: ${{ steps.parse-stack-yml.outputs.aws-account-id }}
  assume-role-arn:
    description: Worker role to assume
    value: ${{ steps.parse-stack-yml.outputs.assume-role-arn }}
  states-bucket:
    description: S3 bucket for Terraform remote state
    value: ${{ steps.parse-stack-yml.outputs.states-bucket }}

runs:
  using: composite
  steps:
    -
      shell: bash
      id: parse-stack-yml
      env:
        INFO_FILE: ${{ inputs.INFO_FILE }}
      run: |
        # Parse info file

        AWS_ACCOUNT_ID=$(cat "$INFO_FILE" | yq '.["aws-account-id"]')
        echo "aws-account-id=$AWS_ACCOUNT_ID" | tee -a "$GITHUB_OUTPUT"

        ASSUME_ROLE_ARN=$(cat "$INFO_FILE" | yq '.["assume-role-arn"]')
        echo "assume-role-arn=$ASSUME_ROLE_ARN" | tee -a "$GITHUB_OUTPUT"

        STATES_BUCKET=$(cat "$INFO_FILE" | yq '.["states-bucket"]')
        echo "states-bucket=$STATES_BUCKET" | tee -a "$GITHUB_OUTPUT"
