name: pr

on:
  pull_request:

permissions:
  contents: read
  id-token: write
  pull-requests: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  lint:
    uses: rx-refill-reminders/pipeline/.github/workflows/check-github-actions.yml@check-github-actions/v0
    with:
      COMPONENT: action
    secrets: inherit

  pr-ready:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v6
      -
        uses: slingshot-pipelines/action-pr-ready@v0
        with:
          NEEDS: ${{ toJSON(needs) }}
